bitzlato/baseapp

public/status/401.html

Add separate page for the 401 error

---

public/config/env.localdev.js
public/config/env.production.js
public/config/env.staging.js

При этом загрузится `trading/<первый маркет>`

Hide the landing page

---

web/jest/setup.tsx
web/src/api/types.ts
web/src/containers/ProfileAuthDetails/index.tsx
web/src/helpers/jest.ts
web/src/mobile/screens/Profile/index.tsx
web/src/routes/Layout/index.tsx

Hide password change when auth0 is enabled

---

web/src/components/PercentageButton/PercentageButton.pcss
web/src/containers/OpenOrders/index.tsx

Эти кнопки добавлял я ещё давно, но не учёл темную тему для них. Пришло время исправиться

Fix Refresh and Close all buttons background for the dark theme

---

web/src/components/CustomInput/__snapshots__/CustomInput.test.tsx.snap
web/src/components/CustomInput/index.tsx
web/src/components/EmailForm/__snapshots__/EmailForm.test.tsx.snap
web/src/components/SignIn/__snapshots__/SignIn.test.tsx.snap
web/src/components/SignUp/__snapshots__/SignUp.test.tsx.snap
web/src/screens/tests/__snapshots__/ChangeForgottenPassword.test.tsx.snap
web/src/screens/tests/__snapshots__/ForgotPassword.test.tsx.snap
web/src/screens/tests/__snapshots__/ProfileScreen.test.tsx.snap
web/src/screens/tests/__snapshots__/ProfileTwoFactorAuthScreen.test.tsx.snap
web/src/screens/tests/__snapshots__/SignInScreen.test.tsx.snap
web/src/screens/tests/__snapshots__/SignUpScreen.test.tsx.snap

Львиная доля измнений - обновление снапшотов

Fix width of the 2FA code for the mobile screen

---

web/.eslintrc.js

Fix ESlint

---

web/package.json
web/src/App.tsx
web/webpack/common.ts
web/yarn.lock

To start to use need to add `bugsnagKey: '<key>'` to env.js

Add ability to use bugsnag

---

web/webpack/common.ts

Do not include large assets in bundle

---

config/deploy/s2.rb

for deploy export env STAGING_SERVER_2

added s2 server

---

web/public/config/env.production.js
web/public/config/env.s2.js
web/public/config/env.staging.js
web/src/api/config.ts
web/src/api/types.ts
web/src/constants/index.ts
web/src/containers/Wallets/EstimatedValue/index.tsx
web/src/helpers/jest.ts
web/src/mobile/components/EstimatedValue/index.tsx

See: https://github.com/bitzlato/peatio/issues/3

Change valuation currencies for Estimated Value 

---

web/src/containers/Header/Header.pcss
web/src/containers/Header/index.tsx
web/src/containers/Order/Order.pcss
web/src/containers/OrderBook/index.tsx
web/src/styles/colors.pcss
web/src/styles/themes/dark.pcss
web/src/styles/themes/light.pcss

Постарался привести цвета в соответствие с дизайном.

Use brandbook colors

---

web/public/config/env.localdev.js
web/public/config/env.production.js
web/public/config/env.s2.js
web/public/config/env.staging.js

Explicit assignments to true are deleted because showLanding by default is true

Switch on the landing page for staging servers

---

web/package.json
web/src/containers/index.ts
web/src/screens/LandingScreen/WelcomeBlock/WelcomeBlock.postcss
web/src/screens/LandingScreen/WelcomeBlock/WelcomeBlock.tsx
web/webpack/development.ts
web/webpack/production.ts
web/yarn.lock

Add chart to the landing page

---

web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
web/src/components/Beneficiaries/index.tsx
web/src/components/Markets/__snapshots__/Markets.test.tsx.snap
web/src/containers/Withdraw/index.tsx
web/src/custom/translations/ru.ts
web/src/screens/WalletsScreen/index.tsx
web/src/translations/en.ts

Change withdrawal address name for the special wallets

---

web/src/containers/Sidebar/Sidebar.postcss
web/src/containers/Sidebar/Sidebar.tsx

- Добавил закрытие сайдбара при нажатии на пункт
- Передвинул сайдбар выше

Fix closing sidebar when you click on item

---

web/src/containers/Footer/Footer.postcss

- Объявил цвета в переменные
- Добавил цвета для светлой темы

Improve styles for footer

---

web/src/custom/translations/ru.ts
web/src/screens/WalletsScreen/WalletsScreen.pcss

Fix word break in the 2FA title (withdraw screen)

---

web/src/components/CurrencyTicker/CurrencyTicker.postcss
web/src/components/CurrencyTicker/CurrencyTicker.tsx
web/src/components/MarketName/MarketName.tsx
web/src/components/Markets/Markets.test.tsx
web/src/components/Markets/__snapshots__/Markets.test.tsx.snap
web/src/components/Markets/index.tsx
web/src/components/OrderForm/index.tsx
web/src/components/Table/index.tsx
web/src/components/TickerTable/index.tsx
web/src/containers/HeaderToolbar/index.tsx
web/src/containers/MarketSelector/MarketSelectorItems/MarketSelectorItems.tsx
web/src/containers/MarketSelector/MarketSelectorTabs/MarketSelectorTab.postcss
web/src/containers/MarketSelector/MarketSelectorTabs/MarketSelectorTab.tsx
web/src/containers/MarketSelector/MarketSelectorToggler/MarketSelectorToggler.tsx
web/src/containers/OrderBook/index.tsx

Add improved currency ticker for token with network

---

web/src/containers/Header/HeaderNavigation/HeaderNavigation.postcss
web/src/containers/Header/HeaderNavigation/HeaderNavigation.tsx
web/src/containers/Header/HeaderNavigation/HeaderNavigationItem.postcss
web/src/containers/Header/HeaderNavigation/HeaderNavigationItem.tsx

Use NavLink in header navigation

---

web/src/assets/icons/CopyIcon.tsx
web/src/components/CopyableTextField/CopyableTextField.test.tsx
web/src/components/CopyableTextField/__snapshots__/CopyableTextField.test.tsx.snap
web/src/components/CopyableTextField/index.tsx
web/src/components/CustomInput/__snapshots__/CustomInput.test.tsx.snap
web/src/components/CustomInput/index.tsx
web/src/components/DepositCrypto/DepositCrypto.pcss
web/src/components/DepositCrypto/index.tsx
web/src/components/EmailForm/__snapshots__/EmailForm.test.tsx.snap
web/src/components/IconButton/IconButton.postcss
web/src/components/IconButton/IconButton.tsx
web/src/components/Markets/__snapshots__/Markets.test.tsx.snap
web/src/components/SignIn/__snapshots__/SignIn.test.tsx.snap
web/src/components/SignUp/__snapshots__/SignUp.test.tsx.snap
web/src/containers/ProfileApiKeys/index.tsx
web/src/containers/ReferralProgram/index.tsx
web/src/custom/translations/ru.ts
web/src/index.pcss
web/src/mobile/components/CreatedApiKeyModal/index.tsx
web/src/mobile/components/WalletDepositBody/index.tsx
web/src/screens/WalletsScreen/index.tsx
web/src/screens/tests/__snapshots__/ChangeForgottenPassword.test.tsx.snap
web/src/screens/tests/__snapshots__/ForgotPassword.test.tsx.snap
web/src/screens/tests/__snapshots__/ProfileScreen.test.tsx.snap
web/src/screens/tests/__snapshots__/ProfileTwoFactorAuthScreen.test.tsx.snap
web/src/screens/tests/__snapshots__/SignInScreen.test.tsx.snap
web/src/screens/tests/__snapshots__/SignUpScreen.test.tsx.snap
web/src/screens/tests/__snapshots__/WalletsScreen.test.tsx.snap
web/src/translations/en.ts

Change Deposit Address field to show the whole text

---

web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
web/src/helpers/validateBeneficiaryAddress.ts

Fix: enable editing the Bitzlato Public Name

---

web/src/components/Button/Button.postcss
web/src/components/Button/Button.tsx
web/src/containers/Header/HeaderNavigation/HeaderNavigation.tsx
web/src/containers/NavBar/NavBar.tsx
web/src/containers/Sidebar/Sidebar.tsx

* Добавил базовый компонент кнопки с цветами по брендбуку
Closed #132

Move sign in / sign up links

---

web/src/index.pcss

Use font-variant-numeric: tabular-nums

---

web/src/components/Beneficiaries/BeneficiariesActivateModal.tsx
web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
web/src/components/Markets/__snapshots__/Markets.test.tsx.snap
web/src/custom/translations/ru.ts
web/src/screens/WalletsScreen/WalletsScreen.pcss
web/src/translations/en.ts

- Remove the Description field
- Rename Beneficiary name to the Address title
- Translate to Russian

Add cosmetic changes to the Withdraw screen

---

web/src/App.tsx

Remove defaultRichTextElements from IntlProvider

---

web/src/components/Beneficiaries/BeneficiariesAddModal.tsx

Hide the Address Title for the bitzlato

---

web/webpack/common.ts

Fix market depths chart

---

web/src/components/CurrencyTicker/CurrencyTicker.tsx
web/src/components/Order/Order.test.tsx
web/src/components/Order/__snapshots__/Order.test.tsx.snap
web/src/components/TickerTable/TickerTable.pcss
web/src/components/TickerTable/index.tsx
web/src/mobile/components/CurrentMarketInfo/index.tsx
web/src/mobile/components/Header/index.tsx
web/src/mobile/styles/components/Charts.pcss
web/src/mobile/styles/components/Header.pcss
web/src/mobile/styles/components/OrderButtons.pcss
web/src/mobile/styles/components/TickerTable.pcss

Fix problems on mobile version

---

web/src/components/CurrencyInfo/index.tsx
web/src/components/DepositCrypto/index.tsx
web/src/components/Order/__snapshots__/Order.test.tsx.snap
web/src/components/OrderInput/__snapshots__/OrderInput.test.tsx.snap
web/src/components/OrderInput/index.tsx
web/src/containers/Charts/index.tsx
web/src/containers/HistoryElement/index.tsx
web/src/containers/ModalWithdrawConfirmation/index.tsx
web/src/containers/Order/Order.pcss
web/src/containers/Sidebar/Sidebar.tsx
web/src/mobile/components/ModalWithdrawConfirmation/index.tsx

Use CurrencyTicker everywhere to display the currency symbol

---

web/src/custom/translations/ru.ts
web/src/translations/en.ts

Fix: translation

---

web/src/components/CryptoCurrencyIcon/CryptoCurrencyIcon.postcss
web/src/components/CryptoCurrencyIcon/CryptoCurrencyIcon.tsx
web/src/components/CurrencyInfo/index.tsx
web/src/components/DepositCrypto/DepositSummary.tsx
web/src/components/WalletItem/WalletItem.tsx
web/src/containers/Footer/Footer.tsx
web/src/containers/OpenOrders/OpenOrders.pcss
web/src/containers/QuickExchange/index.tsx
web/src/custom/translations/ru.ts
web/src/index.pcss
web/src/routes/Layout/index.tsx
web/src/screens/Fees/Fees.postcss
web/src/screens/Fees/index.tsx
web/src/translations/en.ts

Feature: add Fees screen

---

web/src/index.pcss
web/src/mobile/styles/components/Footer.pcss
web/src/mobile/styles/components/OrderButtons.pcss
web/src/mobile/styles/components/WalletsButtons.pcss

fix: show Deposit/Withdraw buttons on mobile

---

web/src/components/CopyableTextField/index.tsx
web/src/containers/Withdraw/BeneficiaryAddress.postcss
web/src/containers/Withdraw/BeneficiaryAddress.tsx
web/src/containers/Withdraw/index.tsx
web/src/custom/translations/ru.ts
web/src/translations/en.ts

Add beneficiary address on withdraw tab

---

web/src/containers/OrdersElement/index.tsx
web/src/mobile/components/Orders/OrdersItem.tsx
web/src/modules/types.ts
web/src/modules/user/openOrders/sagas/userOpenOrdersFetchSaga.ts
web/src/modules/user/ordersHistory/sagas/ordersHistorySaga.ts

Additionally fixed compiler warnings

chore: remove the trigger_wait status of the order

---

web/src/components/Button/Button.postcss
web/src/components/Button/Button.tsx
web/src/components/LockedComponent/index.tsx
web/src/containers/NavBar/NavBar.tsx
web/src/mobile/components/Header/index.tsx
web/src/mobile/components/Profile/ProfileLinks/index.tsx
web/src/mobile/components/Profile/UserInfo/index.tsx
web/src/mobile/screens/Profile/index.tsx
web/src/mobile/styles/components/Header.pcss
web/src/mobile/styles/components/ProfileLinks.pcss

Additional:
- add the property revertLightPrimary which uses secondary button color for the primary variant in the light theme
- change Sign In/Sign Out buttons for the mobile devices

fix: add outline variant for the Button

---

web/src/components/CombinedOrderBook/CombinedOrderBook.pcss
web/src/components/CustomInput/CustomInput.pcss
web/src/components/Label/Label.postcss
web/src/components/Label/Label.tsx
web/src/components/Markets/Markets.pcss
web/src/components/Markets/__snapshots__/Markets.test.tsx.snap
web/src/components/Markets/index.tsx
web/src/components/OrderForm/Input.postcss
web/src/components/Table/Table.pcss
web/src/components/Table/index.tsx
web/src/containers/MarketSelector/MarketSelectorItems/MarketSelectorItems.tsx
web/src/containers/Markets/Markets.pcss
web/src/containers/Order/Order.pcss
web/src/containers/OrderBook/OrderBook.pcss
web/src/containers/ReferralProgram/ReferralProgram.pcss
web/src/index.pcss
web/src/screens/TradingScreen/TradingScreen.pcss
web/src/styles/themes/dark.pcss
web/src/styles/themes/light.pcss

Small stylistic changes mostly for tables on the trading screen

fix: add some stylistic changes

---

web/src/components/DepositCrypto/DepositInvoice.tsx
web/src/modules/user/deposits/actions.ts
web/src/modules/user/deposits/constants.ts
web/src/modules/user/deposits/reducer.test.ts
web/src/modules/user/deposits/reducer.ts
web/src/modules/user/deposits/selectors.ts

Closes #247
Удалил из стора лишнее состояние `success`

fix: enable Create Deposit after the success creating

---

web/src/components/Box/Box.postcss
web/src/components/Box/Box.tsx
web/src/components/CustomInput/CustomInput.pcss
web/src/components/Order/__snapshots__/Order.test.tsx.snap
web/src/components/Order/index.tsx
web/src/components/OrderForm/Input.postcss
web/src/components/OrderForm/OrderForm.pcss
web/src/components/OrderForm/index.tsx
web/src/constants/index.ts
web/src/containers/Order/Order.pcss
web/src/containers/Order/index.tsx
web/src/helpers/fromDecimal.ts
web/src/helpers/order.ts
web/src/mobile/components/OrderButtons/index.tsx
web/src/mobile/components/TradingTabs/Charts/index.tsx
web/src/mobile/styles/components/CreateOrder.pcss
web/src/mobile/styles/components/OrderButtons.pcss
web/src/mobile/styles/components/OrderInput.pcss

fix: do not create an order (market/buy) if the balance is insufficient

---

web/src/components/Box/Box.tsx
web/src/components/Box/index.ts
web/src/components/Label/Label.postcss
web/src/components/Label/Label.tsx
web/src/components/LockedComponent/index.tsx
web/src/components/Order/__snapshots__/Order.test.tsx.snap
web/src/components/OrderForm/OrderForm.pcss
web/src/components/OrderForm/index.tsx
web/src/index.pcss

- размеры задаются явно в px
- на мобилке теперь по умолчанию - 14px

chore: update default font sizes

---

web/mocks/api/v2/peatio/market/orders/GET.mock
web/src/components/Order/__snapshots__/Order.test.tsx.snap
web/src/components/Order/index.tsx
web/src/components/OrderForm/index.tsx
web/src/containers/OpenOrders/index.tsx
web/src/containers/Order/Order.pcss
web/src/containers/OrdersElement/index.tsx
web/src/mobile/components/Orders/OrdersItem.tsx
web/src/modules/helpers.ts
web/src/modules/types.ts

- OrderForm переписан как функциональный компонент (использовался componenWillReceiveProps)
- Исправлена ошибка (креш) при показе маркет ордера в списке Open Orders

Order issues

---

web/src/components/Order/index.tsx
web/src/components/OrderForm/index.tsx
web/src/containers/Order/index.tsx
web/src/helpers/order.ts

https://bitzlato.atlassian.net/browse/EX-125

fix: hide unavailable order types in Order Form (EX-125)

---

web/src/containers/QuickExchange/QuickExchange.tsx
web/src/modules/user/quickExchange/reducer.ts

https://bitzlato.atlassian.net/browse/EX-123

fix: clear amount fields after successful exchange (EX-123)

---

web/src/components/Box/Box.postcss
web/src/components/Box/Box.tsx
web/src/components/CustomInput/index.tsx
web/src/components/NumberInput/NumberInput.postcss
web/src/components/NumberInput/NumberInput.tsx
web/src/containers/QuickExchange/QuickExchange.tsx
web/src/helpers/parseNumeric.test.ts
web/src/helpers/parseNumeric.ts

- add NumberInput component
- add number parsing functions from https://github.com/bitzlato/p2p-mobile/blob/develop/src/utils/parse/parseNumeric.ts
https://bitzlato.atlassian.net/browse/EX-117

fix: validate input values in Quick Exchange (EX-117)

---

web/src/components/Order/Order.test.tsx
web/src/components/Order/__snapshots__/Order.test.tsx.snap
web/src/components/Order/index.tsx
web/src/components/OrderForm/OrderForm.pcss
web/src/components/OrderForm/index.tsx
web/src/containers/Order/Order.pcss
web/src/containers/Order/index.tsx
web/src/containers/QuickExchange/Dropdown.tsx
web/src/custom/translations/ru.ts
web/src/helpers/storageKeys.ts
web/src/translations/en.ts

- show Min Amount
- reduce the precision of Total
- make the default order type is Market and save it to local storage
- use AmountFormat and MoneyFormat
Closes #261

fix: order form improvements

---

web/src/components/Beneficiaries/index.tsx
web/src/components/CustomInput/CustomInput.pcss
web/src/components/NumberInput/NumberInput.postcss
web/src/components/NumberInput/NumberInput.tsx
web/src/containers/QuickExchange/QuickExchange.tsx
web/src/containers/Withdraw/index.tsx
web/src/mobile/components/WalletWithdrawBody/index.tsx
web/src/modules/user/beneficiaries/defaults.ts
web/src/modules/user/beneficiaries/reducer.ts
web/src/screens/WalletsScreen/index.tsx

- Withdraw now is a functional component
- number input uses a monospaced font
- small refactoring
closes #267

chore: use NumberInput in Withdraw form

---

web/public/config/env.localdev.js
web/public/config/env.production.js
web/public/config/env.sandbox.js
web/src/api/config.ts
web/src/api/types.ts
web/src/containers/Header/HeaderNavigation/HeaderNavigation.tsx
web/src/containers/Header/HeaderNavigation/HeaderNavigationItem.postcss
web/src/containers/QuickExchange/AmountDescription.tsx
web/src/containers/QuickExchange/PriceLimit.tsx
web/src/containers/QuickExchange/QuickExchange.postcss
web/src/containers/QuickExchange/QuickExchange.tsx
web/src/containers/QuickExchange/helpers.ts
web/src/containers/Sidebar/Sidebar.tsx
web/src/routes/Layout/index.tsx

https://bitzlato.atlassian.net/browse/EX-128

fix: show Quick Exchange for the unregistered user (EX-128)

---

web/src/routes/Layout/index.tsx
web/src/screens/WalletsScreen/helpers.ts
web/src/screens/WalletsScreen/index.tsx
web/src/screens/tests/__snapshots__/WalletsScreen.test.tsx.snap

fix: select currency from URL on the wallets page

---

web/src/api/requestBuilder.ts
web/src/custom/translations/ru.ts
web/src/helpers/auth0.ts
web/src/modules/public/alert/actions.ts
web/src/modules/public/alert/sagas/handleAlertSaga.ts
web/src/modules/public/errorHandler/sagas/handleErrorSaga.ts
web/src/modules/types.ts
web/src/modules/user/profile/reducer.ts
web/src/modules/user/profile/selectors.ts
web/src/routes/Layout/index.tsx
web/src/screens/SignInScreen/SignInAuth0.tsx
web/src/screens/VerifyEmail/VerifyEmail.tsx
web/src/translations/en.ts

feat: show screen about email verification

---

web/src/components/TickerTable/TickerTable.pcss
web/src/components/TickerTable/index.tsx
web/src/containers/HeaderToolbar/HeaderToolbarItem.postcss
web/src/containers/ProfileVerification/ProfileVerification.pcss
web/src/custom/translations/ru.ts
web/src/mobile/screens/Profile/index.tsx
web/src/mobile/styles/components/Footer.pcss
web/src/mobile/styles/components/ProfileLinks.pcss
web/src/mobile/styles/components/Subheader.pcss
web/src/mobile/styles/components/TradingTabs.pcss
web/src/mobile/translations/en.ts
web/src/mobile/translations/ru.ts
web/src/screens/tests/__snapshots__/SignInScreen.test.tsx.snap
web/src/screens/tests/__snapshots__/SignUpScreen.test.tsx.snap
web/src/translations/en.ts

https://bitzlato.atlassian.net/browse/EX-136

fix: translate to russian (EX-136)

---

web/src/containers/Wallets/EstimatedValue/index.tsx
web/src/helpers/estimateValue.test.ts
web/src/helpers/estimateValue.ts
web/src/mobile/components/EstimatedValue/index.tsx
web/src/screens/tests/__snapshots__/WalletsScreen.test.tsx.snap

fix: reduce precision in estimated value in USD

---

web/src/components/Card/Card.postcss
web/src/components/Card/Card.tsx
web/src/containers/QuickExchange/QuickExchange.postcss
web/src/containers/QuickExchange/QuickExchange.tsx
web/src/helpers/capitalize.test.ts
web/src/helpers/capitalize.ts
web/src/screens/VerifyEmail/VerifyEmail.tsx

additional:
- add capitalize helper function

chore: add size property for the Card

---

web/src/components/Box/Box.postcss
web/src/components/Box/Box.tsx
web/src/components/Card/Card.postcss
web/src/components/Card/Card.tsx
web/src/components/CombinedOrderBook/index.tsx
web/src/components/CryptoCurrencyIcon/CryptoCurrencyIcon.postcss
web/src/components/CryptoCurrencyIcon/CryptoCurrencyIcon.tsx
web/src/components/DepositCrypto/DepositInvoice.tsx
web/src/components/DepositCrypto/DepositSummary.tsx
web/src/components/DepositCrypto/index.tsx
web/src/components/LockedComponent/index.tsx
web/src/components/Order/__snapshots__/Order.test.tsx.snap
web/src/components/OrderForm/index.tsx
web/src/containers/QuickExchange/QuickExchange.tsx
web/src/containers/Withdraw/index.tsx
web/src/mobile/components/Profile/UserActivityItem/index.tsx
web/src/mobile/components/TradingTabs/CreateOrder/index.tsx
web/src/mobile/components/WalletBanner/index.tsx
web/src/mobile/components/WalletDepositBody/index.tsx
web/src/screens/Fees/Fees.tsx
web/src/screens/WalletsScreen/index.tsx

- add props to the Card
- add props to the CryptoCurrencyIcon

chore: reduce props count of the Box (EX-138)

---

web/src/components/Card/Card.postcss
web/src/components/Card/Card.tsx
web/src/containers/Fees/TradingFees.postcss
web/src/containers/Fees/TradingFees.tsx
web/src/mobile/screens/Profile/index.tsx
web/src/mobile/translations/en.ts
web/src/mobile/translations/ru.ts
web/src/routes/Layout/index.tsx
web/src/screens/Fees/Fees.postcss
web/src/screens/Fees/Fees.tsx
web/src/screens/ProfileScreen/ProfileScreen.pcss

fix: add fees screen for the mobile device

---

web/src/components/Box/Box.postcss
web/src/components/Box/Box.tsx
web/src/components/Dropdown/Dropdown.pcss
web/src/components/Dropdown/Dropdown2.tsx
web/src/components/NumberInput/MoneyInput.tsx
web/src/components/NumberInput/NumberInput.postcss
web/src/components/NumberInput/NumberInput.tsx
web/src/components/Order/__snapshots__/Order.test.tsx.snap
web/src/components/OrderForm/index.tsx
web/src/containers/QuickExchange/QuickExchange.tsx

- Renamed as Dropdown2 to avoid duplication
- Added MoneyInput
- Update props of Box
https://bitzlato.atlassian.net/browse/EX-138

chore: move new Dropdown component to common place (EX-138)

---

web/webpack.config.js

added the ability to change the listening interface via env var HOST in makefile start_baseapp block.

express listening interface

---

shared/src/components/Footer/Footer.css.ts
shared/src/components/Footer/Footer.tsx
shared/src/components/Footer/FooterMenu.css.ts
shared/src/components/Footer/FooterMenu.tsx
shared/src/i18n.ts
web/src/components/Header/Header.tsx

feat: Add mobile variant for shared footer

---

web/src/containers/QuickExchange/QuickExchange.tsx
web/src/containers/Wallets/Transfer.tsx

chore: Fix percents select of transfer and exchange components (ex-171)

---

web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
web/src/components/Box/Box.postcss
web/src/components/Box/Box.tsx
web/src/components/Card/Card.tsx
web/src/components/Container/Container.postcss
web/src/components/Container/Container.tsx
web/src/containers/ProfileAccountActivity/index.tsx
web/src/containers/ProfileApiKeys/index.tsx
web/src/containers/QuickExchange/QuickExchange.tsx
web/src/screens/Fees/Fees.tsx
web/src/screens/ProfileScreen/ProfileScreen.postcss
web/src/screens/ProfileScreen/ProfileScreen.tsx
web/src/screens/VerifyEmail/VerifyEmail.tsx
web/src/screens/WalletsScreen/WalletsScreen.tsx
web/src/screens/tests/__snapshots__/ProfileScreen.test.tsx.snap

- Добавил `my` отступы по вертикали в `Box` 
- Убрал `outer` из `Card`
- Добавил компонент `Container`, с его помощью можно контролировать максимальную ширину. Принимает все свойства компонента `Box`

chore: Refactor Card component

---

web/src/components/AmountFormat/AmountFormat.tsx
web/src/components/AmountFormat/getFormatOptionsByLanguage.tsx

feat: Add amount format by language

---

web/src/components/TickerTable/index.tsx
web/src/containers/MarketsTable/index.tsx
web/src/modules/public/markets/types.ts

fix: last price column on tickers table

---

web/src/containers/Wallets/TransferHistory.tsx
web/src/custom/translations/ru.ts
web/src/translations/en.ts

chore: Add translates transfer statuses

---

web/src/containers/Withdraw/Withdraw.tsx
web/src/containers/Withdraw/WithdrawBody.tsx

fix: place beneficiary address higher of blur window

---

web/src/custom/translations/ru.ts

chore: Add russian translates for beneficiaries confirmation [#181199408]

---

web/src/components/Beneficiaries/Beneficiaries.pcss
web/src/components/Blur/Blur.pcss
web/src/index.pcss

fix: blur window on Withdraw overlaps dropdown

---

web/src/components/Container/Container.postcss
web/src/components/Container/Container.tsx
web/src/components/Modal/Modal2.tsx

Стащил размер из Modal. Сам компонент пока не стал использовать, так как в мобильной версии он совсем по другому выглядит

fix: change Modal2 width

---

web/src/components/InternalTransfer/index.tsx
web/src/components/Order/__snapshots__/Order.test.tsx.snap
web/src/components/OrderForm/index.tsx
web/src/components/TabPanel/index.tsx
web/src/containers/Confirm/Documents/index.tsx
web/src/containers/QuickExchange/QuickExchange.tsx
web/src/containers/Wallets/Transfer.tsx

fix: Hide IOS keyboard after click on select [#181308331]

---

README.md
web/public/config/env.localdev.js
web/src/app/template.html
web/webpack.config.js

Чтобы не менять конфигурацию в двух файлах, при переключении PROXY хоста

chore: configure auth0 params using env params

---

web/src/components/MarketDepths/__snapshots__/MarketDepths.test.tsx.snap
web/src/components/MarketDepths/index.tsx

fix: Changed layout of axis X labels [#181308388]

---

web/src/components/Header/Header.tsx
web/src/components/shared/Header/Logo.tsx

- place Beta label inside the link

feat: redirect to p2p from market logo

---

web/src/components/Header/Header.tsx
web/src/components/shared/Header/Header.tsx
web/src/components/shared/Header/Navigation.tsx

feat: Add a link to P2P in header on trade screen

---

web/src/containers/Gift/Gift.tsx
web/src/containers/ProfileAuthDetails/TwoFactorModal.tsx
web/src/custom/translations/ru.ts
web/src/modules/account/voucher-types.ts
web/src/translations/en.ts

- Сузить комментарий
- Добавить возможность указать сумму в фиате
- Обновлять баланс при отмене чека
- Показывать в cashed_by profile_name
- Показывать корректную сумму в фиате (converted_amount поле)
- Сделать ограничение ввода 8 символов после запятой
- На англ версии при просмотре чека перевести в шапке Check на Gift

fix: some issues of Gifts [#181172757]

---

web/src/containers/Gift/Gift.tsx
web/src/hooks/data/useFetchVouchers.ts

Чтобы выявить подтверждение, запрашиваем первый неоплаченный чек и если изменился код, то закрываем диалог.

fix: auto close confiramtion dialog in Gifts [#181172757]

---

web/src/components/Input/TextInput.postcss
web/src/components/Input/TextInput.tsx
web/src/containers/Gift/Gift.tsx

- Если в инпут не введена сумма - не показывать эквивалентно
- Убрать возможность расширения поля ввода комментария текста
- Ограничить ввод коментарий до 200 символов

fix: add some improvements to Gifts [#181695481]

---

web/src/components/Input/TextInput.tsx
web/src/components/profile/ChangePassword.tsx
web/src/components/profile/Profile.tsx
web/src/custom/translations/ru.ts
web/src/hooks/mutations/useChangePassword.ts
web/src/translations/en.ts

feat: Add a form to change password

---

web/src/hooks/data/useFetchTradeStatistics.ts

Сортировка статистике сделок по количеству совершённых сделок

fix: Add sort by totalDeals in ProfileDealsStats

---

web/src/components/profile/Profile.tsx
web/src/components/profile/ProfileDealsStats.tsx
web/src/custom/translations/ru.ts
web/src/hooks/data/useFetchTradeStatistics.ts
web/src/screens/tests/__snapshots__/ProfileScreen.test.tsx.snap
web/src/translations/en.ts

- Показываем только успешные сделки
- Не показываем нулевые количества сделок
- Поправил перевод

fix: Improve deals stats [#181726697]

---

web/src/App.tsx
web/src/helpers/lazyRetry.ts
web/src/screens/DocumentationScreen/index.tsx

Функция призвана побороть ошибки вида 503 Service Unavailable

chore: add lazyRetry function to retry component loading after the fail

---

web/src/components/MoneyFormat/MoneyFormat.tsx

fix: place symbol on currency (like $) before the amount

---

web/src/bootstrap.tsx
web/src/components/app/AppContext.tsx
web/src/components/app/AppContextProvider.tsx
web/src/components/ui/Button.tsx
web/src/components/ui/Modal.tsx
web/src/components/ui/Tooltip.css.ts
web/src/components/ui/Tooltip.tsx
web/src/lib/test/wrapper.tsx
web/src/screens/tests/__snapshots__/ProfileScreen.test.tsx.snap
web/src/theme/colors.ts
web/src/theme/sprinkles.css.ts
web/src/theme/vars.css.ts

- Добавил компонент Tooltip
- Добавил AppContext для использования данных о приложении во вложенных компонентах (минуя redux), полезно для шаред-комопнентов
Как использовать Tooltip:
```ts
<Tooltip label="This is Tooltip" placement="top"><Button>Hover or Focus</Button></Tooltip>
```
Чтобы тултип мог привязаться к позиции и эвентам нужно, чтобы дочерний компонент принимал пропсы: `ref` `onFocus` `onBlur` `onMouseEnter` `onMouseLeave`

Add Tooltip component [#181865630]

---

web/src/containers/Wallets/TransferHistory.tsx

fix: Padding TransferHistory  [#181199535]

---

web/src/components/Box/Box.postcss
web/src/components/Box/Box.tsx
web/src/components/IconButton/IconButton.postcss
web/src/components/IconButton/IconButton.tsx
web/src/components/Input/MoneyInput.postcss
web/src/components/Input/PasswordInput.postcss
web/src/components/Input/PasswordInput.tsx
web/src/components/Input/TextInput.postcss
web/src/components/LockedComponent/index.tsx
web/src/components/Select/Select.postcss
web/src/components/TabPanel/index.tsx
web/src/components/ui/Button.css.ts
web/src/containers/QuickExchange/QuickExchange.postcss
web/src/containers/QuickExchange/QuickExchange.tsx
web/src/index.pcss
web/src/screens/tests/__snapshots__/ProfileScreen.test.tsx.snap
web/src/theme/sprinkles.css.ts
web/src/theme/vars.css.ts

Кнопка, инпут и селек по умолчанию имеют одну высоту

feat: Use same height for controls [#181865546]

---

web/src/components/profile/Profile.tsx
web/src/components/profile/UserSuspicious.tsx
web/src/custom/translations/ru.ts
web/src/screens/tests/__snapshots__/ProfileScreen.test.tsx.snap
web/src/translations/en.ts

Изменил расположение о статусе Подозрительный

fix: Change position of suspicious status [#181726493]

---

web/src/components/DepositCrypto/Deposit.tsx
web/src/components/DepositCrypto/DepositExchange.tsx
web/src/components/DepositCrypto/DepositP2P.tsx
web/src/components/WalletAddress/WalletAddress.tsx
web/src/containers/Wallets/History.tsx
web/src/containers/Wallets/Transfer.tsx
web/src/hooks/useStateWithDeps.ts
web/src/mobile/screens/SelectedWalletScreen/WalletMobileScreen.tsx
web/src/modules/account/types.ts
web/src/screens/WalletsScreen/WalletsScreen.tsx

- На закладке депозитов появился контрол выбора кошелька (P2P/Market)
- Для депозитов история трансферов отображается без закладок

feat: Add selection of deposit address type [#181920594]

---

web/src/containers/Withdraw/Withdraw.tsx
web/src/mobile/screens/SelectedWalletScreen/WalletMobileScreen.tsx
web/src/screens/WalletsScreen/WalletsScreen.tsx

- когда только один вариант вывода, показывать его сразу
- в истории убрать показ закладок, т.к. он зависит от выбора в комбо

fix: Default walletType. Show current walletType history [#181931270]

---

web/src/routes/Layout/index.tsx

- Теперь подставляется путь в форму входа при редиректе с приватных маршрутов
- Экран диплинков стал приватным

feat: Change access to deeplinks screen to private [#181171392]

---

.vim/coc-settings.json
.yarn/sdks/integrations.yml
.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js

https://yarnpkg.com/getting-started/editor-sdks#cocnvim

chore: Add vim integrations config for yarn PnP

---

web/src/components/ui/VariantSwitcher.css.ts
web/src/components/ui/VariantSwitcher.tsx
web/src/screens/tests/__snapshots__/ProfileScreen.test.tsx.snap
web/src/theme/colors.ts
web/src/theme/vars.css.ts

Использовать как просто переключалку, вместо табов:
```ts
const [value, setValue] = useState('info');
<VariantSwitcher
target="tabs"
variants={[
{ label: 'Информация', value: 'info' },
{ label: 'Чат', value: 'chat' },
{ label: 'Заметки', value: 'notes' },
]}
value={value}
onChange={setValue}
/>
```
Как использовать для формы:
```ts
const [value, setValue] = useState('buy');
<VariantSwitcher
target="form"
variants={[
{ label: 'Купить', value: 'buy' },
{ label: 'Продать', value: 'sell' },
]}
value={value}
onChange={setValue}
/>
```

feat: Add ui/VariantSwitcher component

---

web/src/containers/SignUp/SignUp.tsx
web/src/custom/translations/ru.ts
web/src/translations/en.ts

fix: Change text of checkbox with accepting terms of use #182072780

---

web/src/custom/translations/ru.ts
web/src/helpers/codeValidation.ts
web/src/hooks/data/useFetchUsers.ts
web/src/modules/user/profile/types.ts
web/src/screens/EmailVerification/EmailVerificationModal.tsx
web/src/translations/en.ts

feat: use pin code to verify email [#181251816]

---

web/src/components/Input/TextInput.postcss
web/src/components/Input/TextInput.tsx
web/src/components/ui/Modal.tsx
web/src/custom/translations/ru.ts
web/src/routes/Layout/index.tsx
web/src/screens/EmailVerification/EmailVerificationModal.tsx
web/src/theme/sprinkles.css.ts
web/src/translations/en.ts

feat: redesign "Confirm your email" modal [#182245423]

---

web/src/components/shared/Ads/Ads.tsx
web/src/components/shared/Ads/Board.tsx
web/src/components/ui/Pagination.css.ts
web/src/components/ui/Pagination.tsx
web/src/theme/sprinkles.css.ts

Добавил мобильную версию на список объявлений

feat: Add mobile version for Ads list [#181865546]

---

web/src/components/shared/Ads/Board.tsx
web/src/modules/p2p/types.ts
web/src/routes/Layout/index.tsx

Добавил параметры фильтра в виде url: /board/type-cryptocurrency-currency?other-filter-params

fix: Add filter path params to ads filter [#181865520]

---

web/src/components/shared/Ads/Filter.tsx
web/src/hooks/data/useFetchP2PWallets.ts
web/src/hooks/useP2PWalletOptions.ts

feat: Show the  wallet balance equivalent in fiat [#181865520]

---

web/src/components/Select/Select.postcss
web/src/containers/Withdraw/BeneficiariesAddModal.tsx

fix: Fix z-index of Select in dialog

---

web/src/components/shared/Adapter.tsx
web/src/components/shared/Ads/Ad.tsx
web/src/components/shared/Ads/Board.tsx
web/src/components/shared/Trader/Trader.tsx
web/src/components/shared/TraderAds/TraderAds.tsx
web/src/screens/p2p/AdScreen.tsx
web/src/screens/p2p/BoardScreen.tsx
web/src/screens/p2p/TraderScreen.tsx

Вместо импорта react-router используем AdapterContext

fix: Use Adapter context instead of react-router

---

web/src/components/shared/Ads/Board.tsx

Случайно заметил что опять зациклился эффект, изза пустого массива

fix: Unexpected component updates in Board filter changes 2

---

web/src/components/shared/Ads/Ads.tsx
web/src/components/shared/Ads/getLinkToP2PUser.ts
web/src/components/shared/Trades/TradesListItem.tsx

- добавил функцию получения ссылки на p2p юзера

fix: Trades screen fixes

---

web/src/components/shared/Footer/Footer.css.ts
web/src/components/shared/Footer/Footer.tsx
web/src/components/shared/Footer/FooterMenu.css.ts
web/src/components/shared/Footer/FooterMenu.tsx
web/src/components/shared/Header/Header.css.ts
web/src/components/shared/Header/Header.tsx
web/src/components/shared/Header/UserPanel/UserPanel.css.ts
web/src/components/shared/Header/UserPanel/UserPanel.tsx
web/src/theme/sprinkles.css.ts

Убрал условия для широких экранов из sprinkles
Собирается проект быстрее и меньше css генерируется

feat: Remove conditions of wide screens in sprinkles

---

web/src/routes/Layout/index.tsx

Убрал filter параметр из роута /trades/

fix: Remove filter param from Trades route [#181865666]

---

web/src/components/shared/InputDate/InputDate.css.ts
web/src/components/shared/InputDate/InputDate.tsx

fix: Fix input date Fit component warning. Fix styles import

---

web/src/components/shared/Trades/Trades.tsx
web/src/helpers/getTimestamp.ts

Поправил конвертацию даты из ссылки в timestamp (как в фильтре)

fix: Change converting date string to timestamp from url query

---

web/src/components/shared/Trades/Trades.tsx
web/src/components/shared/Trades/TradesFilter.tsx

По умолчанию на странице "Мои сделки" открываются "активные"
В url параметрах onlyClosed заменил на status

fix: Set active trades as default. Change onlyClosed to status url param

---

web/src/App.tsx
web/src/hooks/data/barong/useFetchPublicFeatures.ts
web/src/hooks/useFeatureEnabled.ts
web/src/modules/user/profile/types.ts
web/src/types/featuresToggling.types.ts

```ts
const enabled = useFeatureEnabled('test_feature');
```

feat: Add features toggling [#182025969]

---

web/src/components/SelectCustom/SelectCustom.tsx
web/src/components/TextInputCustom/TextInputCustom.css.ts
web/src/components/TextInputCustom/TextInputCustom.tsx

Добавил отдельно, тк нужен и в другой ветке тоже

fix: Add isError prop to TextInputCustom

---

web/src/components/shared/Chat/ChatControls.tsx

Отправка сообщения - Enter
Перенос строки - Shift/Ctrl + Enter

feat: Now adding a new line with shift/ctrl+enter in textarea chat [#182961530]

---

web/src/screens/GiftsScreen/ActiveGiftsScreen.tsx
web/src/screens/GiftsScreen/GiftsScreen.tsx
web/src/screens/GiftsScreen/HistoryGiftsScreen.tsx

подвинул хлебные крошки на страницах с чеками по границам контейнера

fix: Move breadcrumbs to container in gifts screens

---

.eslintignore
market-docs/src/Swagger.tsx
web/src/App.tsx
web/src/helpers/lazyRetry.ts
web/src/screens/DocumentationScreen/index.tsx
web/src/screens/WalletsStat/WalletsStat.tsx
web/src/screens/p2p/AdScreen.tsx
web/src/screens/p2p/BoardScreen.tsx
web/src/screens/p2p/CreateAdScreen.tsx
web/src/screens/p2p/TraderScreen.tsx
web/src/screens/p2p/TradesScreen.tsx
web/src/screens/p2p/UserAdScreen.tsx
web/src/screens/p2p/UserAdsScreen.tsx

feat: Add P2P Swagger in DocumentationScreen [#183060066]
