bitzlato/baseapp

web/src/api/config.ts, web/src/api/types.ts, web/src/containers/Customization/index.tsx, web/src/helpers/customizationSettings.ts, web/src/helpers/jest.ts, web/src/modules/admin/config/sagas/configUpdateSaga.ts
Включение кнопки настройки цветов:
- открыть devtools браузера (F12)
- перейти на закладку Console
- вбить следующий код: `window.sessionStorage.setItem('palette/show', 'true')`
- перезагрузить страницу
- появится зеленая иконка палитры в правом нижнем углу
Сохранение темы после изменений цветов:
- открыть devtools/Console
- нажать Save
- в консоли появится строчка `palette { theme_colors: {...} ...}`
- над theme_colors вызвать контектное меню > `Copy object`
- получившийся текст можно отправить сообщением
=> Enhancement: show palette editor by sessionStorage value

web/package.json, web/postcss.config.js, web/tsconfig.json, web/yarn.lock
Warnings:
- You did not set any plugins, parser, or stringifier.
- DeprecationWarning: Use of deprecated folder mapping "./" in the "exports"
- Cannot write file '/web/config-overrides.js' because it would overwrite input file.
=> Fix some warnings in the console and editor

web/package.json, web/src/app/template_dev.html, web/webpack/development.ts
При починке команды `yarn start-mock` не учел запуск из devdax. Теперь заведена явная переменная `mock`
=> Fix the loading of env.js for the devdax

web/src/components/WalletItem/index.tsx, web/src/screens/WalletsScreen/WalletsScreen.pcss
Fixes bitzlato/baseapp#39
Ещё подвинул текст ближе к иконке
=> Fix alignment for WalletItem

web/src/modules/public/errorHandler/sagas/handleErrorSaga.ts
По коду, события с типом 'sentry' нигде не вызываются. Добавил вызов на всякий случай
=> Notify bugsnag on special 'sentry' errors

web/.editorconfig, web/.eslintignore, web/index.d.ts, web/jest.config.js, web/package.json, web/public/config/env.localdev.js, web/src/routes/Layout/index.tsx, web/src/screens/NewLandingScreen/NewLandingScreen.postcss, web/src/screens/NewLandingScreen/NewLandingScreen.tsx, web/src/screens/NewLandingScreen/index.ts, web/src/screens/index.ts, web/webpack/development.ts, web/webpack/production.ts, web/yarn.lock
Используем расширение `*.postcss`, другие уже заняты в сборке, а это поддерживается плагином https://marketplace.visualstudio.com/items?itemName=csstools.postcss
Из плгинов пока используем только `postcss-preset-env`, там включен `autoprefixer` и фичи Stage 2+ https://preset-env.cssdb.org/features#stage-2
Тестовый компонент `NewLandingScreen` можно мержить без страха, лендинги у нас везде пока выключены.
=> Add use CSS Modules with postcss

web/.prettierrc, web/webpack/development.ts
- Дополнительный конфиг преттира для форматирования файлов
- `postcss-preset-env` переключил на stage 1, чтобы была доступна вложеность
=> Improve configs for .postcss

web/src/components/History/DepositStatus.tsx, web/src/components/History/ExternalLink.tsx, web/src/components/History/Status.tsx, web/src/components/History/TransferLinks.tsx, web/src/components/Markets/__snapshots__/Markets.test.tsx.snap, web/src/containers/HistoryElement/index.tsx, web/src/containers/Wallets/History.tsx, web/src/containers/Wallets/SucceedIcon.tsx, web/src/custom/translations/ru.ts, web/src/helpers/getBlockchainLink.ts, web/src/helpers/index.ts, web/src/helpers/transferLinks.tsx, web/src/hooks/useT.ts, web/src/mobile/components/HistoryTable/index.tsx, web/src/modules/user/history/types.ts, web/src/translations/en.ts
- Все статусы окрашиваются в три цвета - зеленый, желтый, красный
- Единое отображение для Wallets, History и мобильной версии
Отображение
* `dispatched` - зеленая иконка галочка
* `errored` - красный Errored или `public_message`
* `skipped` - красный Skipped
* `rejected` -красный Сanceled
* `submitted` - желтый `Processing` 
* `invoiced` - желтые `transfer_links` (ссылки)
* `canceled` - красный  Сanceled
* `accepted` - желтый Pending confirmations/min_confirmations (ссылка)
* `refunding` - желтый Refunding
=> Change the deposit status presentation

web/src/app/template.html, web/webpack/common.ts, web/webpack/development.ts, web/webpack/production.ts
При запросе env.js добавляется `?<timestamp>`, чтобы при обновлении env.js не брался старый из кеша
=> Use hash when fetching the env.js

web/webpack/development.ts
Не знаю по какой причине, но origin запроса не менялся и вебсокет соединение сбрасывалось.
Теперь `make start_baseapp_proxy PROXY_HOST=market.bitzlato.com` работает
=> Change header origin while proxying the websocket request

web/package.json, web/scripts/static-server.js, web/webpack/production.ts, web/yarn.lock
Уделён обфускатор кода для работы сорс мапов. Т.к. код у нас открытый использовать его нет смысла.
Потом надо не забыть отключить копирование map файлов, ну или удаление после деплоя
=> Remove the obfuscator to enable the source maps

web/package.json, web/src/components/Documentation/Documentation.pcss, web/src/components/Documentation/Endpoints/DocumentationEndpoints.pcss, web/src/components/Documentation/Endpoints/Item/RequestTypeItem/ParametersItem/index.tsx, web/src/components/Documentation/Endpoints/Item/RequestTypeItem/ResponsesItem/index.tsx, web/src/components/Documentation/Endpoints/Item/RequestTypeItem/index.tsx, web/src/components/Documentation/Endpoints/Item/index.tsx, web/src/components/Documentation/Endpoints/index.tsx, web/src/components/Documentation/Header/DocumentationHeader.pcss, web/src/components/Documentation/Header/index.tsx, web/src/components/Documentation/Models/DocumentationModels.pcss, web/src/components/Documentation/Models/Item/index.tsx, web/src/components/Documentation/Models/index.tsx, web/src/containers/MarketSelector/MarketSelector.postcss, web/src/containers/MarketSelector/MarketSelector.tsx, web/src/containers/MarketSelector/MarketSelectorTabs/MarketSelectorTab.postcss, web/src/containers/MarketSelector/MarketSelectorTabs/MarketSelectorTab.tsx, web/src/containers/MarketSelector/MarketSelectorTabs/MarketSelectorTabs.postcss, web/src/containers/MarketSelector/MarketSelectorTabs/MarketSelectorTabs.tsx, web/src/containers/OpenOrders/OpenOrders.pcss, web/src/screens/DocumentationScreen/DocumentationScreen.pcss, web/src/screens/DocumentationScreen/Swagger.tsx, web/src/screens/DocumentationScreen/WebSocketApi.tsx, web/src/screens/DocumentationScreen/index.tsx, web/yarn.lock
Swagger UI в светлой теме, т.к. у него нет темной версии. Добавлю, только если попросят
Страница по WebSocket тупо создается на основе markdown файла скопированного из peatio репозитория
=> Add Swagger and WebSocket API tabs to the documentation screen

web/src/containers/QuickExchange/AmountDescription.tsx, web/src/containers/QuickExchange/QuickExchange.postcss, web/src/containers/QuickExchange/QuickExchange.tsx, web/src/containers/QuickExchange/helpers.test.tsx, web/src/containers/QuickExchange/helpers.ts
- upper dropdown shows all available currencies
- bottom dropdown shows only existing markets with the upper
- if not found a market with the new upper currency, the bottom will be reset
=> fix: hide absent markets in the "Quick Exchange"

web/package.json, web/webpack.config.js, web/yarn.lock
В `swagger-ui-react` обновлены зависимости, типа `react` `core-js`
`swagger-ui-react` требует `stream`, по-этому добавил фоллбэк `stream-browserify`
=> Update dependecies swagger-ui-react to ^4.3.0

web/.gitignore, web/webpack.config.js
Полезно для сохранения статистики о продакшн билдах и последующего анализа.
Например, как сравнить свою ветку с мастером:
1. Находясь в ветке `master` сделать билд с анализом: `ANALYZE=1 yarn build`
2. Перейти в другую ветку `git checkout feat/foo` и сделать билд с анализом: `ANALYZE=1 yarn build`
3. Теперь можно запустить statoscope чтобы собрать отчет: `yarn dlx @statoscope/cli generate --input statoscope-reports/stats-baseapp-*.json --output statoscope-reports/report.html`
4. Открыть в браузере `statoscope-reports/report.html` и в разделе Diff сравнить две статистики.
=> chore(build): Enable stats saving to internal folder

web/src/components/AmountFormat/AmountFormat.tsx, web/src/components/Format/NoAmountFormat.tsx, web/src/components/WalletItem/WalletItem.tsx, web/src/containers/Withdraw/WithdrawSummary.tsx, web/src/mobile/screens/SelectedWalletScreen/WalletMobileBalance.tsx, web/src/mobile/screens/SelectedWalletScreen/WalletMobileScreen.tsx, web/src/screens/WalletsScreen/Balance.tsx, web/src/screens/WalletsScreen/WalletsScreen.tsx, web/src/screens/WalletsScreen/helpers.ts
Чтобы локализовать использование прочерка, добавил компонент `NoAmountFormat`
=> fix: show dash symbol when no p2p balance [#181157839]

web/src/components/MarketName/MarketName.tsx, web/src/containers/OrdersElement/index.tsx
Изменения понадобились, потому что в текущих маркетах может не найтись ид маркета у ордера, причем у совсем старых вообще нет разделителей
=> fix: change old order's market name

web/src/app/template.html
Исправляю поведение, когда не определена `process.env.AUTH0_DOMAIN`, то подставляется пустая строка `''`
Было
```
window.AUTH0_DOMAIN = '';
window.AUTH0_CLIENT_ID = '';
```
Стало
```
window.AUTH0_DOMAIN = null;
window.AUTH0_CLIENT_ID = null;
```
=> fix: Fix define window.AUTH0_DOMAIN and window.AUTH0_CLIENT_ID

web/src/publicPath.ts, web/webpack.config.js
- `publicPath: 'auto'` нужен, чтобы не было проблем при использовании shared компонентов на p2p
- А чтобы не было проблем с загрузкой чанков на бирже – меняем publicPath на лету
=> fix: Revert publicPath value to 'auto'

web/src/components/profile/Profile.tsx, web/src/components/ui/Text.tsx, web/src/helpers/parseAmount.test.ts, web/src/helpers/parseAmount.ts, web/src/screens/tests/__snapshots__/ProfileScreen.test.tsx.snap, web/src/theme/sprinkles.css.ts
- `parseAmount` - полезная функция, для ограничения цифр после запятой
=> feat: Add truncation of rating line in profile stats

web/src/containers/Gift/Gift.tsx, web/src/custom/translations/ru.ts, web/src/helpers/fetch.ts, web/src/hooks/data/useFetchRate.ts, web/src/modules/user/profile/types.ts, web/src/translations/en.ts
- Писать так же сумму Примерно в фиате
- Кнопки % (25,50,75,100) должны брать сумму от фиата, а не от крипты
- В созданном/обналиченном чеках писать валюту, в которой был создан, а не в USD
- Добавить информативности на две ошибки: нельзя выписать чек в фиате меньше 1 ,а больше чем на кошельке.
- При вводе суммы в фиате - показывать сколько это эквивалентно в крипте
=> fix: add some improvements to Gifts [#181695481]

web/src/containers/Gift/Gift.tsx
This reverts commit c088d41d4ef46dffa19df6fea734bb12d5ff90b6.
Изменили API, добавили поле 
Теперь ответ по линкам такой
```
{
"type": "telegram",
"label": "Telegram bot @xxx",
"url": "xxx"
}
```
=> Revert "fix: Use type property in gift links"

web/src/components/shared/Ads/Board.tsx
=> fix: Set full width for mobile container at Board [#181865520]

web/src/components/shared/Trades/TradesFilter.tsx, web/src/helpers/getTimestamp.ts
фильтр на бэке принимает timestamp независимо от таймзоны (в GMT), а getTime выдает timestamp который вычисляется относительно таймзоны. Поэтому для получения нужной - вычел из getTime - getTimezoneOffset
=> fix: Getting global timestamp in trades filter date

web/src/hooks/data/useFetchP2PCurrencies.ts, web/src/hooks/data/useUserAds.ts, web/src/hooks/useCryptoCurrencies.ts, web/src/hooks/useP2PWalletOptions.ts, web/src/modules/p2p/trade.types.ts, web/src/modules/p2p/types.ts, web/src/types.ts, web/src/types/currencies.types.ts
Переименовал `MoneyCurrency` в `BaseCurrency` и переместил его в отдельный файл `web/src/types/currencies.types.ts`
Планирую в ближайшее время рефакторить запросы на получение валют от бэка и использовать `BaseCurrency` как основной тип для них.
=> chore: Refactoring MoneyCurrency type

web/src/App.tsx
Добавил `AdapterContext`, который выше остальных. Это исправит компонент `TwoFactorModal`, которому нужно использовать `useSharedT`.
`params` тут не прокидываю, т. к. на этом уровне они всегда пустые.
=> fix: Add a top-level AdapterContext

web/src/components/shared/Ads/useBoardFilter.ts
```при открытии ссылки https://bitzlato.bz/en/p2p/buy-btc-rub-tinkoff payment method не применяется из урла, похоже на баг```
- добавил проверку paymethod в эффекте - если его нет а slug есть, то ищем по slug
- добавил в обновление фильтра, очистку paymethodSlug
=> fix: Set paymethod from slug and fix update paymethod slug when removed

web/src/components/shared/Chat/ChatControls.tsx
Оказывается ctrl+enter новую строку не добавляет. Добавил нужное.
=> fix: Fix adding a new line for ctrl+enter in textarea chat [#182961530]

web/src/components/TextInputCustom/DetailsInput.tsx, web/src/components/shared/CreateAd/StepTerms.tsx, web/src/components/shared/UserAd/UserAdRequisitesStep.tsx
Ограничил ввод реквизитов до 30 символов, иначе бэк все равно отрезает до 30 символов
=> fix: Limit input for requisites to 30 symbols
